#!/bin/bash
MANIFEST=git://github.com/HyconOS/manifest.git
BRANCH=eleven
mkdir -p /tmp/rom # Where to sync source
cd /tmp/rom

# Repo init command, that -device,-mips,-darwin,-notdefault part will save you more time and storage to sync, add more according to your rom and choice. Optimization is welcomed! Let's make it quit, and with depth=1 so that no unnecessary things.
repo init --no-repo-verify --depth=1 -u "$MANIFEST" -b "$BRANCH" -g default,-device,-mips,-darwin,-notdefault
git config --global user.name Puneet Gautam
git config --global user.email punitrajgautam@gmail.com

# Clone local manifest! So that no need to manually git clone repos or change hals, you can use normal git clone or rm and re clone, they will cost little more time, and you may get timeout! Let's make it quit and depth=1 too.
#git clone https://github.com/Apon77Lab/android_.repo_local_manifests.git --depth 1 -b aex .repo/local_manifests

# Sync source with -q, no need unnecessary messages, you can remove -q if want! try with -j30 first, if fails, it will try again with -j8
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j$(nproc --all) || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8

git clone https://github.com/kryptoniteX/device_asus_X01BD --single-branch -b hycon device/asus/X01BD
git clone https://github.com/kryptoniteX/device_asus_sdm660-common device/asus/sdm660-common
git clone https://github.com/kryptoniteX/vendor_asus vendor/asus
git clone https://github.com/Shibi404/kernel_asus_sdm660 --single-branch -b perf kernel/asus/X01BD

